name: Artifacts

on:
  workflow_call:
    inputs:
      release:
        description: Whether this is a release build
        default: false
        required: false
        type: boolean

permissions:
  contents: read

jobs:
  binary:
    name: Binary
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Nix
        uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # v27
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Nix shell
        run: nix develop --impure .#ci

      - name: Determine build command
        uses: haya14busa/action-cond@1d6e8a12b20cdb4f1954feef9aa475b9c390cab5 # v1.1.1
        id: build-command
        with:
          cond: ${{ inputs.release }}
          if_true: goreleaser release
          if_false: goreleaser release --skip-publish --snapshot

      - name: Build
        run: nix develop --impure .#ci -c ${{ steps.build-command.outputs.value }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: "[${{ github.job }}] Goreleaser output"
          path: |
            build/dist/*.tar.gz
            build/dist/protoc-gen-twirp_php_checksums.txt
