name: CI (Depot)

on:
  push:
    branches: [master]
  pull_request:

permissions:
  contents: read

env:
  DAGGER_VERSION: 0.18.1

jobs:
  test:
    name: Test
    runs-on: depot-ubuntu-latest,dagger=0.18.1
    strategy:
      fail-fast: false
      matrix:
        php: ["7.4", "8.0", "8.1", "8.2", "8.3", "8.4"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run pipeline
        run: dagger call tests --php-version ${{ matrix.php }} all
        env:
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}

      # - name: Run pipeline
      #   uses: dagger/dagger-for-github@e5153f5610d82ac9f3f848f3a25ad9d696641068 # v7.0.1
      #   with:
      #     verb: call
      #     args: tests --php-version ${{ matrix.php }} all
      #     cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
      #     version: ${{ env.DAGGER_VERSION }}

  lint:
    name: Lint
    runs-on: depot-ubuntu-latest,dagger=0.18.1

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run pipeline
        run: dagger call lint all
        env:
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}

      # - name: Run pipeline
      #   uses: dagger/dagger-for-github@e5153f5610d82ac9f3f848f3a25ad9d696641068 # v7.0.1
      #   with:
      #     verb: call
      #     args: lint all
      #     cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
      #     version: ${{ env.DAGGER_VERSION }}
