name: Static analysis

on:
  push:
    branches: [master]
  pull_request:

permissions:
  contents: read

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Nix
        uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # v27
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Set up magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@87e8236f46702ab0ce5a058b605a173ec88d618e # v6

      - name: Prepare Nix shell
        run: nix develop --impure .#ci_lowest

      - name: Download dependencies
        run: nix develop --impure .#ci_lowest -c composer update --no-interaction --no-progress

      - name: Run PHPStan
        run: nix develop --impure .#ci_lowest -c phpstan analyze --no-progress

  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Nix
        uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # v27
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Set up magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@87e8236f46702ab0ce5a058b605a173ec88d618e # v6

      - name: Prepare Nix shell
        run: nix develop --impure .#ci_lowest

      - name: Download dependencies
        run: nix develop --impure .#ci_lowest -c composer update --no-interaction --no-progress

      - name: Run PHP CS Fixer
        run: nix develop --impure .#ci_lowest -c php-cs-fixer fix --diff --dry-run

  # psalm:
  #   name: Psalm
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
  #
  #     - name: Set up Nix
  #       uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # v27
  #       with:
  #         extra_nix_config: |
  #           access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
  #
  #     - name: Set up magic Nix cache
  #       uses: DeterminateSystems/magic-nix-cache-action@87e8236f46702ab0ce5a058b605a173ec88d618e # v6
  #
  #     - name: Prepare Nix shell
  #       run: nix develop --impure .#ci_lowest
  #
  #     - name: Download dependencies
  #       run: nix develop --impure .#ci_lowest -c composer update --no-interaction --no-progress
  #
  #     - name: Run Psalm
  #       run: nix develop --impure .#ci_lowest -c psalm --no-progress --root $PWD --output-format=github
